config {
    type: "incremental",
    description: "Dataform creates a temporary incremental_example that updates incrementally, and deletes the table after 30 days from its creation"
}

SELECT
  DATE(timestamp) AS date,
  event_name
FROM
  dataform.tablewithtimestamp
  ${
      when(
          incremental(), `WHERE timestamp > (SELECT max(date) FROM ${self()})`
      )
  }

post_operations {
  DELETE
  FROM
    ${self()}
  WHERE
    date < (DATE_ADD(Day,-30, CURRENT_DATE))
}
